### ISSUE TITLE
Initial thoughts on DB Schema

### ISSUE THREAD

**Issue by MichaelSchwar3** [stephenchung27/discode#1]
Add prospective dates and how long you intend to work on each MVP in MVP List

Username
Do we need both username and e-mail or just one?

ServerMemberShips
Do we need to call the foreign key member? Or can we use user_id? Perhaps would make it easier when creating the association so you don’t have to wonder what you called the foreign key during the association

Servers
Why is the server_name an integer?
Can a server have many admins rather than belong to a user?

ChannelMessages
Author_id to user_id for same reason as above.

 You’re going to have to do some research in regards to how to configure these voice channels. However, I would focus on getting your main MVPs complete and then perhaps adding the bonuses once you go into the job search

Great work on this schema, just some minor changes to be made. The bonus MVPs will be tough and would only move on to them if you think your primary MVPs are perfect. Let me know if you want to discuss any of the feedback.

**Comment by stephenchung27** [comment]
**Username**
I wanted to follow the apparent schema that Discord uses as closely as possible but it's true that I would not need an e-mail. Discord allows for users to use a non-unique alias but adds a four digit integer to the end to ensure uniqueness so I was considering maybe making an after_initialize validation or a username= method that adds the "salt" to the end of the username then making the email the main login credential. This would require more work for me but seems relatively simple to implement so I'd appreciate your thoughts on this.

I was initially thinking about using <class>_id for my foreign keys but was unsure if this was the actual convention used in most companies. I'd think making the column names more explicit would help reduce confusion for other team members when I start working but Rails does the association magic for us if we use <class>_id's. Do you have any insight on what would be the preferred method? 

**Servers**
Discord servers have moderators but only a single admin so I was thinking user_id might be ambiguous. Having moderators was a big reason why I have a bonus "Roles" table in my schema but for the time being I think one admin would be the best approach.

I actually made the decision to do Discord maybe a month ago and have started researching the WebRTC api which allows live voice chat. Do you have any experience with the technology by any chance? 

**Direct Messages**
I was having trouble naming the columns of the two users within a direct message. In my schema I have sender_id and receiver_id but once a direct message is made the names would become arbitrary. I was thinking about putting a unique index on the ids of both users so that a duplicate direct message with the sender/receiver switched around would not occur. Would that be sufficient or would I have to create a model level validation that checks if the combination exists already? Also would that naming schema be more semantic than calling them first_user and second_user?

Sorry for the massive wall of text... I want to make my final project really impressive especially since there are two other extremely smart people doing Discord.

**Comment by MichaelSchwar3** [comment]
As far as convention, it really depends on the company you're working for. Everyone will have their own convention, I was merely making an observation and what made more sense to me. However, if you feel like it would make more sense to you to keep as is, then that's the way I would keep it. At the end of the day, no recruiter is going to dissect your code to the point of convention on foreign keys, but they will dissect your app in regards to functionality and display. So if you think your way will allow you to work better//faster, then I would say keep as is.

For your server admins, that is a fair point, you can leave as is but take a look at the following functionality built into Rails to see if this may help in some way.
https://api.rubyonrails.org/v5.2.2/classes/ActiveRecord/Enum.html

In regards to WebRTC api, I asked around and it doesn't appear that anyone has any experience using this API, however I would recommend using the built in rails functionality of action cables and web sockets as much as you can for the chat functionality, and only rely on this API when necessary, as I'm not sure how rails will handle the voice portion. 

As for how to handle the direct messaging, I would take inspiration from previous discord//slack apps.
Here is one app that had at the minimum a functional direct messaging portion and the DB was setup well.
https://github.com/Benpong89/slang/blob/master/db/schema.rb

Let me know if you're having any trouble navigating what is happening in this schema

**Comment by stephenchung27** [comment]
- [ ] fgdfgsfgsfg

- [ ] sdfgsdfgsdfgs

**Comment by MichaelSchwar3** [comment]
Updated schema looks good, going to close this issue for now. Keep in mind this is not the end all be all for your schema, things will definitely change as you build the project
